// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJmlCrrEdNKPZfH-bqwO-Q10M6IDO21f0',
    appId: '1:22263571597:web:96f9dd02d09155067c2ec4',
    messagingSenderId: '22263571597',
    projectId: 'food-recipe-7787c',
    authDomain: 'food-recipe-7787c.firebaseapp.com',
    storageBucket: 'food-recipe-7787c.firebasestorage.app',
    measurementId: 'G-5VC3ZQT7PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByot-IdL9Zlz3io5fx6wx_VhqtL2rJDmg',
    appId: '1:22263571597:android:880df8c448ac62a67c2ec4',
    messagingSenderId: '22263571597',
    projectId: 'food-recipe-7787c',
    storageBucket: 'food-recipe-7787c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtO_u-A8XrFsZXeL9ZeZ_NC5M_7sTQ8fI',
    appId: '1:22263571597:ios:3dbfc4594dd519837c2ec4',
    messagingSenderId: '22263571597',
    projectId: 'food-recipe-7787c',
    storageBucket: 'food-recipe-7787c.firebasestorage.app',
    iosBundleId: 'com.example.foods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtO_u-A8XrFsZXeL9ZeZ_NC5M_7sTQ8fI',
    appId: '1:22263571597:ios:3dbfc4594dd519837c2ec4',
    messagingSenderId: '22263571597',
    projectId: 'food-recipe-7787c',
    storageBucket: 'food-recipe-7787c.firebasestorage.app',
    iosBundleId: 'com.example.foods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJmlCrrEdNKPZfH-bqwO-Q10M6IDO21f0',
    appId: '1:22263571597:web:e42ce37372b087c27c2ec4',
    messagingSenderId: '22263571597',
    projectId: 'food-recipe-7787c',
    authDomain: 'food-recipe-7787c.firebaseapp.com',
    storageBucket: 'food-recipe-7787c.firebasestorage.app',
    measurementId: 'G-1XH3Q7TDJ0',
  );

}